### PR TITLE
Fix display Gatling Reports, close gatling/gatling#3154

### PR DESCRIPTION
**Pull request by ccedric**

### CODE REVIEW

**Comment by slandelle** [comment]
Could you please elaborate on the issue (how it was introduced)?

**Comment by ccedric** [comment]
The issue is a regression from 38d7a9c25bf89a4b8c32b85451c3218089e13071.
I also fixed an issue related to the size of the reports in the newer versions of Jenkins.

**Comment by slandelle** [comment]
Please check build failure (findbugs): https://jenkins.ci.cloudbees.com/job/plugins/job/gatling-plugin/57/org.jenkins-ci.plugins$gatling/findbugsResult/new/

**Comment by ccedric** [comment]
Fixed

**Comment by danielbcorreia** [comment]
Hi, I'm also having this issue and would really like this to be merged. Are there any pending issues with this pull request?

**Comment by slandelle** [comment]
@ccedric Could you please squash your commits?

**Comment by ccedric** [comment]
@slandelle Squashed.

**Pull request merged**
